### ISSUE TITLE
[1.10.2] Crash when trying to Create a SP World

### ISSUE THREAD

**Issue by Morpheus1101** [Mysteryem/Up_And_Down_And_All_Around#46] opened 2016-10-17 08:40 UTC
Crash log @ http://pastebin.com/xZs9tnhw

**Comment by Mysteryem** [comment] 2016-10-17 11:14
Well that sure doesn't make any sense to me. That would seem to imply that the player does not have a ```GravityDirectionCapability```, which, as far as I know, is impossible.

I can't reproduce it with the current (1.7.2) MMD dev server pack, have you added any extra mods to the pack?

I should be able to make a build of the mod later that will crash the instant a ```GravityAxisAlignedBB``` is created with a null ```GravityDirectionCapability```, which should track down where the issue is originating from.

Code is run in this order:

1. ```EntityPlayerMP``` constructor calls it's super class' constructor
1. At the end of the ```Entity``` constructor, forge gathers capabilities via its ```AttachCapabilitiesEvent```
1. I add the capability in my event listener and set the player's bounding box to a ```GravityAxisAlignedBB``` in the capability's initialiser: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/gravitymod/capabilities/GravityCapabilityEventHandler.java#L28
1. Code in the ```EntityPlayerMP``` constuctor (after the super class' constructor has been called) is run
1. This leads code which gets the player's bounding box and calls the ```expand``` method on it
1. This calls my overridden ```expand``` method
1. NPE occurs here due to the ```GravityDirectionCapability``` being null: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/gravitymod/util/GravityAxisAlignedBB.java#L73 (the direction can't be null as far as I can see, unless the API is used to set the direction to null or it's set to null during one of the mod's gravity events, both things I should change, though they're not used by any mods right now. Reading a gravity direction from invalid nbt or packets would throw an IndexOutOfBoundsException, preventing them from setting it to null)

**Comment by Morpheus1101** [comment] 2016-10-17 11:21
it was MMD but with a few mods updated and removed and at this point there is so many things that go haywire updating the pack etc i left it be as more mods need some newer updates for issues arisen that are known.  So further info i cant say...if id rememberd i should've included the fml-client-latest

**Comment by Mysteryem** [comment] 2016-10-17 12:12
Try https://www.dropbox.com/s/brciefqah0ka5cz/UpAndDownAndAllAround-2.0.jar?dl=0

It may not even crash at all, as I made a change to how I deal with the fact that Entities try to set their bounding boxes before forge adds capabilities to them, which other mods might have been able to mess with.

I gave it a quick test and it seemed to work fine in SSP and SMP when on its own. Didn't test with the current MMD dev server mod pack yet as I've got some things to do right now.

Let me know how it goes.

**Comment by Mysteryem** [comment] 2016-10-22 09:02
In https://github.com/Mysteryem/Up_And_Down_And_All_Around/commit/7511ad062bf0caf7c0ea5b4d630d5be280f3aad0 I've added a [check in the EntityPlayerWithGravity constructor](https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/7511ad062bf0caf7c0ea5b4d630d5be280f3aad0/src/main/java/uk/co/mysterymayhem/gravitymod/asm/EntityPlayerWithGravity.java#L45) for if the player doesn't have the GravityDirectionCapability. In that case, it will crash (this mod won't work at all if I let it pass without the capability) and attempt to point out that my mod is not at fault here (the code I added cannot physically be run until after capabilities have been added). So I'm closing this issue.

**Closed by Mysteryem** 2016-10-22 09:02 UTC
Labels: bug, high priority
