### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Drakoflame** [Mysteryem/Up_And_Down_And_All_Around#52] opened 2017-02-02 22:48 UTC
Dunno what happened! http://pastebin.com/bpW1H1ds

Crashed upon starting up

**Comment by Mysteryem** [comment] 2017-02-03 00:07
Does it work fine with just my mod removed?

Try without CreativeCore and ItemPhysic, I found someone who had posted another crash log with the same crash and those two coremods are present in both that crash and this one (https://minecraft.curseforge.com/projects/better-with-mods?comment=209).

I'll look into what I can on my end, but I'll need you to dissect your modpack to help track down the cause.

**Comment by Drakoflame** [comment] 2017-02-03 01:49
it works fine without your mod. I'm thinking it might have something to do with ItemPhysics, as I've had two other crashes and this last one was involving Tinkers construct, but it gave me a very very similar error that it would give me with Underground biomes construct... so I'm going to try deleting item physics and see how thigns work

**Comment by Drakoflame** [comment] 2017-02-03 02:15
FOLLOWUP: no crash on startup with Up Down and All Around installed. I'll report these issues to Creative

**Comment by Mysteryem** [comment] 2017-02-03 11:24
I've commented on https://github.com/CreativeMD/ItemPhysic/issues/27 with more details. I'll close this issue for now.

**Closed by Mysteryem** 2017-02-03 11:24 UTC
